name: worflow L8
on: 
  push:
    branches:
      - master
jobs:
  mis_tests:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USUARIODOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}

      - name: Build and push Docker image
        run: |
          docker build -t as-laboratorio8-web ./app/
          docker tag as-laboratorio8-web ${{ secrets.USUARIODOCKER }}/as-laboratorio8-web:latest
          docker push ${{ secrets.USUARIODOCKER }}/as-laboratorio8-web:latest

