name: worflow L8
on: 
  push:
    branches:
      - master
jobs:
  mis_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USUARIODOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}

 