name: worflow L8
on: 
  push:
    branches:
      - master
jobs:
  mis_tests:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USUARIODOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}

      - name: Build and push Docker image
        run: |
          docker build -t as-laboratorio8-web ./app/
          docker tag as-laboratorio8-web ${{ secrets.USUARIODOCKER }}/as-laboratorio8-web:latest
          docker push ${{ secrets.USUARIODOCKER }}/as-laboratorio8-web:latest


      - name: Login to GCE
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.ID_REPO }}
          credentials_json: ${{ secrets.KUBERNETES_ADMIN }}

      - name: Login to Kubernetes
        uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Configurar kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: l8cluster
          location: us-east1

          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/db-deployment.yaml
          kubectl apply -f ./k8s/frontend-deployment.yaml
          kubectl rollout restart deployment redis
          kubectl rollout restart deployment frontend